/*
 * optimize_view.c - Optimization control view with async solver
 */

#include "optimize_view.h"
#include "pieces_view.h"
#include "results_view.h"
#include "../cutter_window.h"
#include "../../csp_types.h"
#include "../../colgen.h"
#include "../../db.h"
#include <math.h>

/* Tolerance for floating-point comparison (0.01mm) */
#define DOUBLE_EPSILON 0.01
#define DOUBLE_EQ(a, b) (fabs((a) - (b)) < DOUBLE_EPSILON)

struct _OptimizeView {
    GtkBox parent_instance;

    GtkWidget *use_inventory_check;
    GtkWidget *kerf_spin;
    GtkWidget *min_offcut_spin;
    GtkWidget *check_button;
    GtkWidget *optimize_button;
    GtkWidget *progress_bar;
    GtkWidget *progress_label;

    /* Problems display */
    GtkWidget *problems_frame;
    GtkWidget *problems_text;

    CutterWindow *main_window;
    gboolean solving;

    /* Solver data - use pointers to avoid huge struct size */
    CSPInstance *instance;
    CSPSolution *solution;
};

G_DEFINE_TYPE(OptimizeView, optimize_view, GTK_TYPE_BOX)

typedef struct {
    OptimizeView *view;
    CSPInstance *instance;
    CSPParameters params;
    CSPSolution *solution;
    int result;
} SolverData;

static gboolean solver_complete(gpointer user_data)
{
    SolverData *data = user_data;
    OptimizeView *self = data->view;

    self->solving = FALSE;
    gtk_widget_set_sensitive(self->optimize_button, TRUE);
    gtk_progress_bar_set_fraction(GTK_PROGRESS_BAR(self->progress_bar), 1.0);

    if (data->result == 0) {
        gtk_label_set_text(GTK_LABEL(self->progress_label), "Optimisation terminée !");

        /* Copy instance (contains patterns generated by solver) */
        memcpy(self->instance, data->instance, sizeof(CSPInstance));

        /* Copy solution */
        if (self->solution == NULL) {
            self->solution = g_new0(CSPSolution, 1);
        }
        memcpy(self->solution, data->solution, sizeof(CSPSolution));

        /* Update results view */
        GtkWidget *stack = gtk_widget_get_parent(GTK_WIDGET(self));
        GtkWidget *results = gtk_stack_get_child_by_name(GTK_STACK(stack), "résultats");
        if (results) {
            results_view_set_solution(CUTTER_RESULTS_VIEW(results),
                                       self->instance, self->solution);
        }

        /* Switch to results view */
        cutter_window_show_view(self->main_window, "résultats");
        cutter_window_set_status(self->main_window,
            g_strdup_printf("Optimisation terminée: %d barres, rendement %.1f%%",
                            self->solution->num_bars_used, self->solution->efficiency));
    } else {
        gtk_label_set_text(GTK_LABEL(self->progress_label), "Erreur lors de l'optimisation");
        cutter_window_set_status(self->main_window, "Erreur d'optimisation");
    }

    g_free(data->instance);
    g_free(data->solution);
    g_free(data);

    return G_SOURCE_REMOVE;
}

static gpointer solver_thread(gpointer user_data)
{
    SolverData *data = user_data;

    data->result = colgen_solve(data->instance, data->params, data->solution);

    /* Schedule completion on main thread */
    g_idle_add(solver_complete, data);

    return NULL;
}

static void clear_problems(OptimizeView *self)
{
    GtkTextBuffer *buffer = gtk_text_view_get_buffer(GTK_TEXT_VIEW(self->problems_text));
    gtk_text_buffer_set_text(buffer, "", -1);
    gtk_widget_set_visible(self->problems_frame, FALSE);
}

static void add_problem(OptimizeView *self, const char *text)
{
    GtkTextBuffer *buffer = gtk_text_view_get_buffer(GTK_TEXT_VIEW(self->problems_text));
    GtkTextIter end;
    gtk_text_buffer_get_end_iter(buffer, &end);

    if (gtk_text_buffer_get_char_count(buffer) > 0) {
        gtk_text_buffer_insert(buffer, &end, "\n", -1);
        gtk_text_buffer_get_end_iter(buffer, &end);
    }
    gtk_text_buffer_insert(buffer, &end, text, -1);
    gtk_widget_set_visible(self->problems_frame, TRUE);
}

static gboolean check_pieces_compatibility(OptimizeView *self)
{
    clear_problems(self);

    /* Get pieces view */
    GtkWidget *stack = gtk_widget_get_parent(GTK_WIDGET(self));
    GtkWidget *pieces = gtk_stack_get_child_by_name(GTK_STACK(stack), "pièces");
    if (!pieces || pieces_view_get_count(CUTTER_PIECES_VIEW(pieces)) == 0) {
        add_problem(self, "Aucune pièce à découper");
        return FALSE;
    }

    /* Initialize temporary instance (allocate on heap due to large size) */
    CSPInstance *temp_instance = g_new0(CSPInstance, 1);
    csp_instance_init(temp_instance);
    temp_instance->saw_kerf = gtk_spin_button_get_value(GTK_SPIN_BUTTON(self->kerf_spin));

    /* Fill pieces */
    pieces_view_fill_instance(CUTTER_PIECES_VIEW(pieces), temp_instance);

    /* Load stock */
    if (!gtk_check_button_get_active(GTK_CHECK_BUTTON(self->use_inventory_check))) {
        add_problem(self, "Sélectionnez une source de stock");
        g_free(temp_instance);
        return FALSE;
    }

    int ns = db_load_inventory(temp_instance);
    if (ns <= 0) {
        add_problem(self, "Stock vide - ajoutez du stock");
        g_free(temp_instance);
        return FALSE;
    }

    /* Debug: print loaded stocks */
    /* Disabled for performance
    g_print("DEBUG: Loaded %d stocks, num_stocks=%d\n", ns, temp_instance->num_stocks);
    for (int s = 0; s < temp_instance->num_stocks; s++) {
        const StockBar *stock = &temp_instance->stocks[s];
        g_print("  Stock %d: %s - diameter=%.1f, thickness=%.1f, material=%d, length=%.1f, qty=%d\n",
                s, stock->label, stock->diameter, stock->thickness, stock->material, stock->length, stock->quantity);
    }
    */

    gboolean all_ok = TRUE;
    char buf[512];

    /* First pass: check each piece has at least one compatible stock */
    for (int i = 0; i < temp_instance->num_pieces; i++) {
        const PieceDemand *piece = &temp_instance->pieces[i];
        gboolean found_compatible = FALSE;
        double max_stock_length = 0;

        /* Debug: disabled for performance
        if (strstr(piece->label, "Q64")) {
            g_print("DEBUG Q64: piece diameter=%.1f, thickness=%.1f, material=%d, length=%.1f\n",
                    piece->diameter, piece->thickness, piece->material, piece->length);
        }
        */

        for (int s = 0; s < temp_instance->num_stocks; s++) {
            const StockBar *stock = &temp_instance->stocks[s];
            gboolean dims_match = (piece->diameter == 0 && piece->thickness == 0) ||
                                  (DOUBLE_EQ(piece->diameter, stock->diameter) &&
                                   DOUBLE_EQ(piece->thickness, stock->thickness));
            /* Check material matches (UNKNOWN matches anything) */
            gboolean mat_match = (piece->material == MATERIAL_UNKNOWN ||
                                  stock->material == MATERIAL_UNKNOWN ||
                                  piece->material == stock->material);

            /* Debug: disabled for performance
            if (strstr(piece->label, "Q64") && stock->diameter >= 99.9 && stock->diameter <= 100.1) {
                g_print("DEBUG Q64 vs %s: stock diameter=%.1f, thickness=%.1f, material=%d, length=%.1f\n",
                        stock->label, stock->diameter, stock->thickness, stock->material, stock->length);
                g_print("  dims_match=%d, mat_match=%d, length_ok=%d\n",
                        dims_match, mat_match, stock->length >= piece->length);
            }
            */

            if (dims_match && mat_match) {
                if (stock->length > max_stock_length) {
                    max_stock_length = stock->length;
                }
                if (stock->length >= piece->length) {
                    found_compatible = TRUE;
                }
            }
        }

        if (!found_compatible) {
            all_ok = FALSE;
            if (piece->diameter > 0) {
                if (max_stock_length > 0 && piece->length > max_stock_length) {
                    snprintf(buf, sizeof(buf),
                             "INCOMPATIBLE: %s (%.0fmm, D%.0fx%.1f) - longueur > stock max %.0fmm",
                             piece->label, piece->length, piece->diameter,
                             piece->thickness, max_stock_length);
                } else {
                    snprintf(buf, sizeof(buf),
                             "INCOMPATIBLE: %s (%.0fmm, D%.0fx%.1f) - aucun stock compatible",
                             piece->label, piece->length, piece->diameter, piece->thickness);
                }
            } else {
                snprintf(buf, sizeof(buf),
                         "INCOMPATIBLE: %s (%.0fmm) - longueur supérieure à tout stock",
                         piece->label, piece->length);
            }
            add_problem(self, buf);
        }
    }

    /* Second pass: group pieces by dimension+material and check stock availability */
    /* Track which dimension groups we've already checked */
    gboolean checked_dims[MAX_PIECE_TYPES] = {FALSE};

    for (int i = 0; i < temp_instance->num_pieces; i++) {
        if (checked_dims[i]) continue;

        const PieceDemand *piece_i = &temp_instance->pieces[i];
        double dim_diameter = piece_i->diameter;
        double dim_thickness = piece_i->thickness;
        MaterialType dim_material = piece_i->material;

        /* Calculate total length needed for all pieces with same dimensions+material */
        double total_length_needed = 0;
        int total_pieces = 0;

        for (int j = i; j < temp_instance->num_pieces; j++) {
            const PieceDemand *piece_j = &temp_instance->pieces[j];
            gboolean same_dims = (DOUBLE_EQ(piece_j->diameter, dim_diameter) &&
                                  DOUBLE_EQ(piece_j->thickness, dim_thickness) &&
                                  piece_j->material == dim_material);
            if (same_dims) {
                checked_dims[j] = TRUE;
                total_length_needed += (piece_j->length + temp_instance->saw_kerf) * piece_j->quantity;
                total_pieces += piece_j->quantity;
            }
        }

        /* Calculate stock available for this dimension+material */
        double total_stock_available = 0;
        double max_stock_length = 0;
        int total_bars_available = 0;
        gboolean unlimited = FALSE;
        char stock_list[256] = "";
        int stock_list_len = 0;

        for (int s = 0; s < temp_instance->num_stocks; s++) {
            const StockBar *stock = &temp_instance->stocks[s];
            /* Check dimensions match */
            gboolean dims_match = (dim_diameter == 0 && dim_thickness == 0) ||
                                  (DOUBLE_EQ(dim_diameter, stock->diameter) &&
                                   DOUBLE_EQ(dim_thickness, stock->thickness));
            /* Check material matches (UNKNOWN matches anything) */
            gboolean mat_match = (dim_material == MATERIAL_UNKNOWN ||
                                  stock->material == MATERIAL_UNKNOWN ||
                                  dim_material == stock->material);
            if (dims_match && mat_match) {
                if (stock->quantity < 0) {
                    unlimited = TRUE;
                }
                if (stock->length > max_stock_length) {
                    max_stock_length = stock->length;
                }
                if (stock->quantity > 0) {
                    total_stock_available += stock->length * stock->quantity;
                    total_bars_available += stock->quantity;
                    /* Build stock list */
                    if (stock_list_len < 200) {
                        int added = snprintf(stock_list + stock_list_len,
                                             sizeof(stock_list) - stock_list_len,
                                             "%s%s(x%d)",
                                             stock_list_len > 0 ? ", " : "",
                                             stock->label, stock->quantity);
                        if (added > 0) stock_list_len += added;
                    }
                }
            }
        }

        /* Estimate minimum bars needed (rough approximation) */
        int estimated_bars_needed = 0;
        if (max_stock_length > 0) {
            estimated_bars_needed = (int)((total_length_needed + max_stock_length - 1) / max_stock_length);
        }

        /* Check if stock is sufficient */
        if (!unlimited) {
            const char *mat_str = material_to_string(dim_material);
            gboolean is_tube = (dim_diameter > 0);

            if (total_bars_available == 0) {
                /* No stock at all for this dimension */
                all_ok = FALSE;
                if (is_tube) {
                    snprintf(buf, sizeof(buf),
                             "MANQUE: Aucun stock pour %.0fx%.1f %s\n  Besoin: ~%d barres (%.0fmm total, %d pièces)",
                             dim_diameter, dim_thickness, mat_str,
                             estimated_bars_needed, total_length_needed, total_pieces);
                } else {
                    snprintf(buf, sizeof(buf),
                             "MANQUE: Aucun stock disponible\n  Besoin: ~%d barres (%.0fmm total, %d pièces)",
                             estimated_bars_needed, total_length_needed, total_pieces);
                }
                add_problem(self, buf);
            } else if (total_length_needed > total_stock_available ||
                       estimated_bars_needed > total_bars_available) {
                /* Insufficient stock */
                all_ok = FALSE;
                if (is_tube) {
                    snprintf(buf, sizeof(buf),
                             "INSUFFISANT %.0fx%.1f %s:\n  Besoin: ~%d barres (%.0fmm)\n  Stock: %d barres (%.0fmm)\n  Dispo: %s",
                             dim_diameter, dim_thickness, mat_str,
                             estimated_bars_needed, total_length_needed,
                             total_bars_available, total_stock_available, stock_list);
                } else {
                    snprintf(buf, sizeof(buf),
                             "INSUFFISANT:\n  Besoin: ~%d barres (%.0fmm)\n  Stock: %d barres (%.0fmm)\n  Dispo: %s",
                             estimated_bars_needed, total_length_needed,
                             total_bars_available, total_stock_available, stock_list);
                }
                add_problem(self, buf);
            }
        }
    }

    if (all_ok) {
        gtk_label_set_text(GTK_LABEL(self->progress_label), "Vérification OK - prêt à optimiser");
    } else {
        gtk_label_set_text(GTK_LABEL(self->progress_label), "Problèmes détectés (voir ci-dessous)");
    }

    g_free(temp_instance);
    return all_ok;
}

static void on_check_clicked(GtkButton *button, gpointer user_data)
{
    (void)button;
    OptimizeView *self = CUTTER_OPTIMIZE_VIEW(user_data);
    check_pieces_compatibility(self);
}

static void on_optimize_clicked(GtkButton *button, gpointer user_data)
{
    (void)button;
    OptimizeView *self = CUTTER_OPTIMIZE_VIEW(user_data);

    if (self->solving) return;

    /* Get pieces view */
    GtkWidget *stack = gtk_widget_get_parent(GTK_WIDGET(self));
    GtkWidget *pieces = gtk_stack_get_child_by_name(GTK_STACK(stack), "pièces");
    if (!pieces || pieces_view_get_count(CUTTER_PIECES_VIEW(pieces)) == 0) {
        gtk_label_set_text(GTK_LABEL(self->progress_label),
                           "Erreur: Ajoutez des pièces a découper d'abord");
        return;
    }

    /* Initialize instance */
    if (self->instance == NULL) {
        self->instance = g_new0(CSPInstance, 1);
    }
    csp_instance_init(self->instance);
    self->instance->saw_kerf = gtk_spin_button_get_value(GTK_SPIN_BUTTON(self->kerf_spin));
    self->instance->min_usable_offcut = gtk_spin_button_get_value(GTK_SPIN_BUTTON(self->min_offcut_spin));

    /* Fill pieces */
    pieces_view_fill_instance(CUTTER_PIECES_VIEW(pieces), self->instance);

    /* Load stock */
    if (gtk_check_button_get_active(GTK_CHECK_BUTTON(self->use_inventory_check))) {
        int ns = db_load_inventory(self->instance);
        if (ns <= 0) {
            gtk_label_set_text(GTK_LABEL(self->progress_label),
                               "Erreur: Stock vide, ajoutez du stock");
            return;
        }
    } else {
        gtk_label_set_text(GTK_LABEL(self->progress_label),
                           "Erreur: Sélectionnez une source de stock");
        return;
    }

    /* Check feasibility */
    if (!colgen_check_feasibility(self->instance)) {
        gtk_label_set_text(GTK_LABEL(self->progress_label),
                           "Erreur: Certaines pièces ne correspondent à aucun stock");
        return;
    }

    /* Start solver */
    self->solving = TRUE;
    gtk_widget_set_sensitive(self->optimize_button, FALSE);
    gtk_progress_bar_set_fraction(GTK_PROGRESS_BAR(self->progress_bar), 0.0);
    gtk_label_set_text(GTK_LABEL(self->progress_label), "Optimisation en cours...");
    cutter_window_set_status(self->main_window, "Optimisation en cours...");

    /* Prepare solver data */
    SolverData *data = g_new0(SolverData, 1);
    data->view = self;
    data->instance = g_memdup2(self->instance, sizeof(CSPInstance));
    data->solution = g_new0(CSPSolution, 1);
    data->params = csp_default_params();
    data->params.verbose = FALSE;

    /* Start thread */
    g_thread_new("solver", solver_thread, data);

    /* Pulse progress bar */
    gtk_progress_bar_pulse(GTK_PROGRESS_BAR(self->progress_bar));
}

static void optimize_view_class_init(OptimizeViewClass *klass)
{
    (void)klass;
}

static void optimize_view_init(OptimizeView *self)
{
    gtk_orientable_set_orientation(GTK_ORIENTABLE(self), GTK_ORIENTATION_VERTICAL);
    gtk_widget_set_margin_start(GTK_WIDGET(self), 12);
    gtk_widget_set_margin_end(GTK_WIDGET(self), 12);
    gtk_widget_set_margin_top(GTK_WIDGET(self), 12);
    gtk_widget_set_margin_bottom(GTK_WIDGET(self), 12);
    gtk_box_set_spacing(GTK_BOX(self), 18);

    self->solving = FALSE;

    /* Title */
    GtkWidget *title = gtk_label_new("Optimisation");
    gtk_widget_add_css_class(title, "title-2");
    gtk_label_set_xalign(GTK_LABEL(title), 0);
    gtk_box_append(GTK_BOX(self), title);

    /* Main content box */
    GtkWidget *content = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 24);
    gtk_widget_set_vexpand(content, FALSE);
    gtk_widget_set_size_request(content, -1, 150);  /* Fixed minimum height */
    gtk_box_append(GTK_BOX(self), content);

    /* Left: Stock source */
    GtkWidget *left_frame = gtk_frame_new("Source du Stock");
    GtkWidget *left_box = gtk_box_new(GTK_ORIENTATION_VERTICAL, 6);
    gtk_widget_set_margin_start(left_box, 12);
    gtk_widget_set_margin_end(left_box, 12);
    gtk_widget_set_margin_top(left_box, 12);
    gtk_widget_set_margin_bottom(left_box, 12);

    self->use_inventory_check = gtk_check_button_new_with_label("Utiliser le stock");
    gtk_check_button_set_active(GTK_CHECK_BUTTON(self->use_inventory_check), TRUE);
    gtk_box_append(GTK_BOX(left_box), self->use_inventory_check);

    gtk_frame_set_child(GTK_FRAME(left_frame), left_box);
    gtk_box_append(GTK_BOX(content), left_frame);

    /* Right: Parameters */
    GtkWidget *right_frame = gtk_frame_new("Paramètres");
    GtkWidget *right_grid = gtk_grid_new();
    gtk_grid_set_row_spacing(GTK_GRID(right_grid), 6);
    gtk_grid_set_column_spacing(GTK_GRID(right_grid), 12);
    gtk_widget_set_margin_start(right_grid, 12);
    gtk_widget_set_margin_end(right_grid, 12);
    gtk_widget_set_margin_top(right_grid, 12);
    gtk_widget_set_margin_bottom(right_grid, 12);

    gtk_grid_attach(GTK_GRID(right_grid), gtk_label_new("Trait de scie (mm):"), 0, 0, 1, 1);
    self->kerf_spin = gtk_spin_button_new_with_range(0, 20, 0.5);
    gtk_spin_button_set_value(GTK_SPIN_BUTTON(self->kerf_spin), 5.0);
    gtk_grid_attach(GTK_GRID(right_grid), self->kerf_spin, 1, 0, 1, 1);

    gtk_grid_attach(GTK_GRID(right_grid), gtk_label_new("Chute min utile (mm):"), 0, 1, 1, 1);
    self->min_offcut_spin = gtk_spin_button_new_with_range(0, 1000, 10);
    gtk_spin_button_set_value(GTK_SPIN_BUTTON(self->min_offcut_spin), 100.0);
    gtk_grid_attach(GTK_GRID(right_grid), self->min_offcut_spin, 1, 1, 1, 1);

    gtk_frame_set_child(GTK_FRAME(right_frame), right_grid);
    gtk_box_append(GTK_BOX(content), right_frame);

    /* Buttons box */
    GtkWidget *buttons_box = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 12);
    gtk_widget_set_halign(buttons_box, GTK_ALIGN_CENTER);

    /* Check button */
    self->check_button = gtk_button_new_with_label("VERIFIER");
    gtk_widget_set_size_request(self->check_button, 150, 50);
    g_signal_connect(self->check_button, "clicked", G_CALLBACK(on_check_clicked), self);
    gtk_box_append(GTK_BOX(buttons_box), self->check_button);

    /* Optimize button */
    self->optimize_button = gtk_button_new_with_label("OPTIMISER");
    gtk_widget_add_css_class(self->optimize_button, "suggested-action");
    gtk_widget_add_css_class(self->optimize_button, "title-1");
    gtk_widget_set_size_request(self->optimize_button, 200, 60);
    g_signal_connect(self->optimize_button, "clicked", G_CALLBACK(on_optimize_clicked), self);
    gtk_box_append(GTK_BOX(buttons_box), self->optimize_button);

    gtk_box_append(GTK_BOX(self), buttons_box);

    /* Progress */
    GtkWidget *progress_box = gtk_box_new(GTK_ORIENTATION_VERTICAL, 6);

    self->progress_bar = gtk_progress_bar_new();
    gtk_progress_bar_set_show_text(GTK_PROGRESS_BAR(self->progress_bar), FALSE);
    gtk_box_append(GTK_BOX(progress_box), self->progress_bar);

    self->progress_label = gtk_label_new("Pret");
    gtk_label_set_xalign(GTK_LABEL(self->progress_label), 0);
    gtk_box_append(GTK_BOX(progress_box), self->progress_label);

    gtk_box_append(GTK_BOX(self), progress_box);

    /* Problems frame (hidden by default) */
    self->problems_frame = gtk_frame_new("Problèmes détectés");
    gtk_widget_add_css_class(self->problems_frame, "error");
    gtk_widget_set_visible(self->problems_frame, FALSE);
    gtk_widget_set_vexpand(self->problems_frame, TRUE);

    GtkWidget *problems_scroll = gtk_scrolled_window_new();
    gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(problems_scroll),
                                    GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
    gtk_widget_set_size_request(problems_scroll, -1, 150);
    gtk_widget_set_vexpand(problems_scroll, FALSE);

    self->problems_text = gtk_text_view_new();
    gtk_text_view_set_editable(GTK_TEXT_VIEW(self->problems_text), FALSE);
    gtk_text_view_set_cursor_visible(GTK_TEXT_VIEW(self->problems_text), FALSE);
    gtk_text_view_set_wrap_mode(GTK_TEXT_VIEW(self->problems_text), GTK_WRAP_WORD_CHAR);
    gtk_widget_set_margin_start(self->problems_text, 8);
    gtk_widget_set_margin_end(self->problems_text, 8);
    gtk_widget_set_margin_top(self->problems_text, 8);
    gtk_widget_set_margin_bottom(self->problems_text, 8);

    gtk_scrolled_window_set_child(GTK_SCROLLED_WINDOW(problems_scroll), self->problems_text);
    gtk_frame_set_child(GTK_FRAME(self->problems_frame), problems_scroll);

    gtk_box_append(GTK_BOX(self), self->problems_frame);
}

GtkWidget *optimize_view_new(gpointer main_window)
{
    OptimizeView *self = g_object_new(CUTTER_TYPE_OPTIMIZE_VIEW, NULL);
    self->main_window = CUTTER_WINDOW(main_window);
    return GTK_WIDGET(self);
}
